### ISSUE TITLE
LoadReads

### ISSUE THREAD

**Issue by amitblum** [philippdre/omniCLIP#4]
Hello, 
I have problems with importing "LoadReads"
Can you pint me please to the module that I should Install?

Thanks
Amit

**Comment by philippdre** [comment]
Dear Amit,

the module is part of omniCLIP and should be found if you run omniLIP. Could you please tell on which data and how you call omniCLIP.  Could you also please tell me, which version of the required modules you have installed?

Best regards,
Philipp

**Comment by amitblum** [comment]
Dear Philipp,
Thanks for the reply.
I think that I solved it. it was just about fix the PATH of the sys.path.append.
Best
Amit
