### ISSUE TITLE
gene = Sequences.keys()[0]  IndexError: list index out of range

### ISSUE THREAD

**Issue by CharlotteAnne** [philippdre/omniCLIP#5]
Hi, when running the program I get this error - do you know where it might come from?

```
setting seed
Loading gene annotation
Memory usage: 101400 (kb)
Loading reads
Parsing the gene annotation
Saving results
Loading coverage only
Parsing the gene annotation
Saving results
Masking overlapping positions
Removing genes without CLIP coverage
Done: Elapsed time: 0.0399670600891
Memory usage: 103216 (kb)
Initialising the parameters
Traceback (most recent call last):
  File "omniCLIP.py", line 930, in <module>
    run_omniCLIP(args)
  File "omniCLIP.py", line 209, in run_omniCLIP
    gene = Sequences.keys()[0]
IndexError: list index out of range
```

Thanks for your help! -Charlotte

**Comment by philippdre** [comment]
Dear Charlotte,

I suspect that there is a problem with the gene annotation. Could you please tell me which data you are using and how you are calling omniCLIP?

Best regards,
Philipp

**Comment by slebedeva** [comment]
Hi Charlotte! I had the same problem when using segemehl aligner. This had to do with the way CIGAR string is written by the aligner. For example, one record of my alignment file that failed:

```
216183-3	256	chr1	10290	1	21=	*	0	0	CCAACCCCAACCCCAACCCCA	*	HI:i:1	NH:i:13	NM:i:0	MD:Z:21	RG:Z:A1	YZ:Z:0
```

And (same read) that worked:
```
216183-3	256	chr1	10290	1	21M	*	0	0	CCAACCCCAACCCCAACCCCA	*	HI:i:1	NH:i:13	NM:i:0	MD:Z:21	RG:Z:A1	YZ:Z:0
```
P.S. in case of segemehl, one needs to include option --briefcigar
