### ISSUE TITLE
different strand for CLIP and input

### ISSUE THREAD

**Issue by slebedeva** [philippdre/omniCLIP#6]
I would like to use stranded mode. However, most CLIP libraries sequence the forward strand, whereas RNA-seq often sequences the reverse strand. There is no possibility to set different --rev-strand option for foreground and background in omniCLIP.

**Comment by santataRU** [comment]
Thanks for raising this question. My PAR-CLIP library is sequenced on the forward strand (single-end), whereas in the stranded RNA-seq protocol (dUTP), read 2 in each pair corresponds to the sense strand. Could I ask what values you used for `--rev_strand`?

My current understanding is that I should use `--rev_strand 0` for both parsingBG and parsingCLIP, but I am not completely sure whether I am on the right track.

`omniCLIP parsingBG --help  ` 
usage: PROG parsingBG [-h] [--rev_strand {0,1}] [--collapsed] [--ign_out_rds]
                      [--max-mismatch MAX_MM]
                      [--mask_flank_mm MASK_FLANK_VARIANTS] --bg-files BG_LIBS
                      --db-file DB_FILE --out-file OUT_FILE
                      [--genome-dir GENOME_DIR] [--bck-var]

Parsing the background files.

optional arguments:
  -h, --help            show this help message and exit
  --rev_strand {0,1}    Only consider reads on the forward (0) or reverse
                        strand (1) relative to the gene orientation
  --collapsed           Reads are collapsed
  --ign_out_rds         ignore reads where the ends map ouside of the genes
  --max-mismatch MAX_MM
                        Maximal number of mismatches that is allowed per read
                        (default: 2)
  --mask_flank_mm MASK_FLANK_VARIANTS
                        Do not consider mismatches in the N bp at the ends of
                        reads for diagnostic event modelling (default: 3)
  --bck-var             Parse variants for background reads

required arguments:
  --bg-files BG_LIBS    BAM files for background libraries
  --db-file DB_FILE     Path to the .GFF.DB file
  --out-file OUT_FILE   Output path for .dat file
  --genome-dir GENOME_DIR
                        Directory where fasta files are stored


`omniCLIP parsingCLIP --help`
usage: PROG parsingCLIP [-h] [--rev_strand {0,1}] [--collapsed]
                        [--ign_out_rds] [--max-mismatch MAX_MM]
                        [--mask_flank_mm MASK_FLANK_VARIANTS] --clip-files
                        CLIP_LIBS --db-file DB_FILE --out-file OUT_FILE
                        [--genome-dir GENOME_DIR] [--mask-miRNA]
                        [--mask-ovrlp] [--min-coverage MIN_COVERAGE]
                        [--min-peak MIN_PEAK]

Parsing the CLIP files.

optional arguments:
  -h, --help            show this help message and exit
  --rev_strand {0,1}    Only consider reads on the forward (0) or reverse
                        strand (1) relative to the gene orientation
  --collapsed           Reads are collapsed
  --ign_out_rds         ignore reads where the ends map ouside of the genes
  --max-mismatch MAX_MM
                        Maximal number of mismatches that is allowed per read
                        (default: 2)
  --mask_flank_mm MASK_FLANK_VARIANTS
                        Do not consider mismatches in the N bp at the ends of
                        reads for diagnostic event modelling (default: 3)
  --mask-miRNA          Mask miRNA positions
  --mask-ovrlp          Ignore overlapping gene regions for diagnostic event
                        model fitting
  --min-coverage MIN_COVERAGE
                        Minimum summed coverage on a whole gene to be
                        considered in the analysis
  --min-peak MIN_PEAK   Minimum maximum peak heigth on a gene to be considered
                        in the analysis

required arguments:
  --clip-files CLIP_LIBS
                        BAM files for CLIP libraries
  --db-file DB_FILE     Path to the .GFF.DB file
  --out-file OUT_FILE   Output path for .dat file
  --genome-dir GENOME_DIR
                        Directory where fasta files are stored
